#!/bin/sh
# Zinteractive — fzf-based setup wizard

_zi_setup() {
  [ "${ZI_HAS_FZF:-0}" = "0" ] && echo "fzf required for setup wizard." && return 1

  local config_dir="$HOME/.config/zinteractive"
  local config_file="$config_dir/config.sh"
  mkdir -p "$config_dir"

  echo "=== Zinteractive Setup ==="
  echo "Press Ctrl+C to skip — defaults will be used."
  echo ""

  # Step 1: Shell
  local detected_shell="zsh"
  [ -n "$FISH_VERSION" ] && detected_shell="fish"
  local shell_choice
  shell_choice=$(printf "zsh (detected)\nfish" | sed "s/^${detected_shell}/${detected_shell} (detected)/" | fzf --header="Select your shell:" --height=10 --no-sort)
  shell_choice=$(echo "$shell_choice" | sed 's/ (detected)//')
  [ -z "$shell_choice" ] && shell_choice="$detected_shell"

  # Step 2: Terminal
  local detected_term="none"
  case "${TERM_PROGRAM:-}" in
    ghostty)     detected_term="ghostty" ;;
    iTerm.app)   detected_term="iterm2" ;;
    WezTerm)     detected_term="wezterm" ;;
    xterm-kitty) detected_term="kitty" ;;
  esac
  local term_choice
  term_choice=$(printf "ghostty\niterm2\nwezterm\nkitty\nnone" | sed "s/^${detected_term}/${detected_term} (detected)/" | fzf --header="Select your terminal:" --height=12 --no-sort)
  term_choice=$(echo "$term_choice" | sed 's/ (detected)//')
  [ -z "$term_choice" ] && term_choice="$detected_term"

  # Step 3: Theme
  local theme_choice
  theme_choice=$(printf "dracula (default)\ncatppuccin\nnord\ngruvbox\nplain" | fzf --header="Select color theme:" --height=12 --no-sort)
  theme_choice=$(echo "$theme_choice" | sed 's/ (default)//')
  [ -z "$theme_choice" ] && theme_choice="dracula"

  # Step 4: Builtin groups
  local builtins_choice
  builtins_choice=$(printf "git\nnav\naws\npickers" | fzf --multi --header="Select builtin groups (TAB to toggle):" --height=12 --no-sort)
  if [ -z "$builtins_choice" ]; then
    builtins_choice="git,nav,aws,pickers"
  else
    builtins_choice=$(echo "$builtins_choice" | tr '\n' ',' | sed 's/,$//')
  fi

  # Step 5: Keybindings
  local bind_palette=1 bind_filepick=1 bind_branchpick=1
  local keybind_choice
  keybind_choice=$(printf "Ctrl+\\\\ (palette)\nCtrl+F (file picker)\nCtrl+B (branch picker)" | fzf --multi --header="Select keybindings to ENABLE (TAB to toggle):" --height=10 --no-sort)
  echo "$keybind_choice" | grep -q "palette" || bind_palette=0
  echo "$keybind_choice" | grep -q "file" || bind_filepick=0
  echo "$keybind_choice" | grep -q "branch" || bind_branchpick=0
  [ -z "$keybind_choice" ] && bind_palette=1 && bind_filepick=1 && bind_branchpick=1

  # Write config
  cat > "$config_file" << EOF
# Zinteractive config — generated by setup wizard
export ZI_SHELL="$shell_choice"
export ZI_TERMINAL="$term_choice"
export ZI_THEME="$theme_choice"
export ZI_BUILTINS="$builtins_choice"
export ZI_BIND_PALETTE=$bind_palette
export ZI_BIND_FILEPICK=$bind_filepick
export ZI_BIND_BRANCHPICK=$bind_branchpick
EOF

  echo ""
  echo "Config saved to $config_file"
  echo "Restart your shell or run: source $config_file"
}
